apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oaj-secret-file
  namespace: conatrib
spec:
  parameters:
    secrets: |
      - resourceName: "projects/842127079591/secrets/oaj-credentials/versions/latest"
        path: "credentials.txt"
  provider: gke
