apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: oaj-app-backendconfig
  namespace: conatrib
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    requestPath: /login
    port: 8080
