steps:
  - name: 'php:8.3.6-cli'
    id: 'php-syntax-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        find . -name "*.php" -not -path "./vendor/*" -not -path "./deploy/*" -exec php -l {} \; || exit 1
        echo "Verificación de sintaxis PHP completada"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-sonar-token'
    waitFor: ['php-syntax-check']
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="sonar-sigj-agent-token" > /workspace/sonar-token.txt

  - name: 'sonarsource/sonar-scanner-cli:latest'
    id: 'sonar-analysis'
    waitFor: ['get-sonar-token']
    entrypoint: bash
    args:
      - '-c'
      - |
        mkdir -p /tmp/sonar-scanner-work
        chmod 777 /tmp/sonar-scanner-work
        SONAR_TOKEN=$(cat /workspace/sonar-token.txt)

        sonar-scanner \
          -Dsonar.projectKey=${_SONAR_PROJECT_KEY} \
          -Dsonar.sources=. \
          -Dsonar.exclusions=vendor/**,tests/**,storage/**,bootstrap/cache/**,deploy/** \
          -Dsonar.host.url=${_SONAR_HOST_URL} \
          -Dsonar.working.directory=/tmp/sonar-scanner-work \
          -Dsonar.token=$$SONAR_TOKEN

  - name: gcr.io/cloud-builders/docker
    id: 'docker-build'
    waitFor: ['php-syntax-check']
    args:
      - build
      - '-f'
      - 'deploy/docker/Dockerfile'
      - '-t'
      - 'northamerica-south1-docker.pkg.dev/tsjcdmx-k8s-prd/conatrib/oaj:${_IMAGE_VERSION}'
      - '.'

  - name: gcr.io/cloud-builders/docker
    id: 'docker-push'
    waitFor: ['docker-build']
    args:
      - push
      - >-
        northamerica-south1-docker.pkg.dev/tsjcdmx-k8s-prd/conatrib/oaj:${_IMAGE_VERSION}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'deploy-apply'
    waitFor: ['docker-push']
    entrypoint: gcloud
    args:
      - deploy
      - apply
      - '--file=deploy/cicd/clouddeploy.yaml'
      - '--region=northamerica-south1'
      - '--project=tsjcdmx-k8s-prd'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'create-release'
    waitFor: ['deploy-apply']
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - 'oaj-release-${_RELEASE_VERSION}'
      - '--project=tsjcdmx-k8s-prd'
      - '--region=northamerica-south1'
      - '--delivery-pipeline=oaj-cd'
      - '--skaffold-file=deploy/skaffold.yaml'
      - '--images=app-image=northamerica-south1-docker.pkg.dev/tsjcdmx-k8s-prd/conatrib/oaj:${_IMAGE_VERSION}'

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/tsjcdmx-k8s-prd/locations/northamerica-south1/workerPools/gitlab-private-tsjcdmx-pool'

substitutions:
  _DEPLOYMENT_ENV: dev
  _IMAGE_VERSION: '1.0.0-${BUILD_ID:0:8}'
  _RELEASE_VERSION: '${BUILD_ID:0:8}'
  _SONAR_PROJECT_KEY: 'oaj'
  _SONAR_HOST_URL: 'http://sonarqube.tsjcdmx-internal.gob.mx:8000/'
